### ISSUE TITLE
Add a possibility to build the RPM package with --nocheck

### ISSUE THREAD

**Issue by rholy** [Tojaj/librepo#49]
Since we build librepo as part of our continuous integration process and the tests of librepo are failing there very often (and also we don't need the tests to pass for our purpose) it would be nice if we could tell ```utils/make_rpm.sh``` to build the RPM with the ```rpmbuild```'s ```--nocheck``` switch.

I can create a pull request. Just tell me how would you prefer to do that. Should I add a switch to ```utils/make_rpm.sh``` that enables ```--nocheck``` or should I add an argument that may contain all additional switches passed to ```rpmbuild```?

**Comment by rholy** [comment]
We've added the following workaround in the meantime: https://github.com/rholy/dnf-ci/commit/4ed11070a14705787c730fb882cad03d9287de22
Please note that librepo's tests are disabled from now.

**Comment by Tojaj** [comment]
--without tests is now supported by spec file #56

**Comment by Tojaj** [comment]
let's use:
utils/make_rpm.sh . '--without tests'

**Comment by rholy** [comment]
Works for me. Thank you!
