### ISSUE TITLE
Unable to handle "file:/path"-like URLs

### ISSUE THREAD

**Issue by rholy** [Tojaj/librepo#55]
According to RFC 3986, it seems that URLs like "file:/path/to/file" (note the missing double slash) are valid too. However it seems that ```lr_handle_prepare_urls``` is not able to handle them.

For more details, see https://bugzilla.redhat.com/show_bug.cgi?id=1205341#c3 . The reporter hit this with DNF which calls ```librepo.Handle.perform``` with the given URL.

**Comment by Tojaj** [comment]
Thanks
