### ISSUE TITLE
dependency on python-flask

### ISSUE THREAD

**Issue by cgwalters** [Tojaj/librepo#56]
Currently python-flask is not in RHEL7, and we're just using it to be a simple webserver for tests.  Would you be OK with a change to use `python -m SimpleHTTPServer` or so?

**Comment by cgwalters** [comment]
How about this on the Fedora epel7 branch for now?

From 134e7828430d813d8072300eeb2062bf4e91d451 Mon Sep 17 00:00:00 2001
From: Colin Walters <walters@verbum.org>
Date: Tue, 14 Apr 2015 11:54:11 -0400
Subject: [PATCH] Disable tests and drop python-flask build dependency on
 RHEL7, as

  it is not in the core
---
 librepo.spec | 13 ++++++++++++-
 1 file changed, 12 insertions(+), 1 deletion(-)

diff --git a/librepo.spec b/librepo.spec
index 8a825e0..03f4c99 100644
--- a/librepo.spec
+++ b/librepo.spec
@@ -4,13 +4,16 @@
 %if 0%{?rhel} != 0 && 0%{?rhel} <= 7
 # Do not build bindings for python3 for RHEL <= 7
 %bcond_with python3
+# python-flask is not in RHEL7
+%bcond_with tests
 %else
 %bcond_without python3
+%bcond_without tests
 %endif
 
 Name:           librepo
 Version:        1.7.14
-Release:        1%{?dist}
+Release:        2%{?dist}
 Summary:        Repodata downloading library
 
 Group:          System Environment/Libraries
@@ -56,8 +59,10 @@ Summary:        Python bindings for the librepo library
 Group:          Development/Languages
 BuildRequires:  pygpgme
 BuildRequires:  python2-devel
+%if %{with tests}
 BuildRequires:  python-flask
 BuildRequires:  python-nose
+%endif
 BuildRequires:  python-sphinx
 BuildRequires:  pyxattr
 Requires:       %{name}%{?_isa} = %{version}-%{release}
@@ -103,6 +108,7 @@ popd
 %endif
 
 %check
+%if %{with tests}
 make ARGS="-V" test
 
 %if %{with python3}
@@ -110,6 +116,7 @@ pushd py3
 make ARGS="-V" test
 popd
 %endif
+%endif
 
 %install
 make install DESTDIR=$RPM_BUILD_ROOT
@@ -141,6 +148,10 @@ popd
 %endif
 
 %changelog
+* Tue Apr 14 2015 Colin Walters <walters@redhat.com> - 1.7.14-2
+- Disable tests and drop python-flask build dependency on RHEL7, as
+  it is not in the core
+
 * Wed Feb   25 2015 Tomas Mlcoch <tmlcoch at redhat.com> - 1.7.14-2
 - compat: fix ck_assert_msg() segfault in rhel-7
 
-- 
1.8.3.1

**Comment by Tojaj** [comment]
I've updated the spec.
Thanks Colin!

The first build with the updated spec (rawhide) is here:
http://koji.fedoraproject.org/koji/taskinfo?taskID=9711052
