### ISSUE TITLE
change description to something meaningful

### ISSUE THREAD

**Issue by nonchip** [Tojaj/librepo#63]
there's no such thing as a "linux repository", but after digging through the docs A LOT it seems this is for redhat/fedora YUM repos? anyway you should make clear what this lib does without having users read the actual apidocs to find out.

**Comment by Tojaj** [comment]
Done

**Comment by nonchip** [comment]
@Tojaj this is actually not done. both the repo description and the readme still state this library is for "packages and linux repository metadata", which does not exist. again: please state which kind of repository/repositories this library supports.
